export const candidates = [
  {
    id: 'cand-1',
    organizationId: '1',
    fullName: 'Ayesha Rahman',
    email: 'ayesha.rahman@example.com',
    phone: '+880170000001',
    location: 'Dhaka, Bangladesh',
    headline: 'Frontend Engineer · React/TypeScript',
    source: 'Referral',
    currentCompany: 'PixelForge',
    currentTitle: 'Senior Frontend Engineer',
    linkedinUrl: 'https://www.linkedin.com/in/ayesha-rahman',
    githubUrl: 'https://github.com/ayesha-frontend',
    yearsExperience: 6,
    tags: ['React', 'TypeScript', 'UI'],
  },
  {
    id: 'cand-2',
    organizationId: '1',
    fullName: 'Rohan Mehta',
    email: 'rohan.mehta@example.com',
    phone: '+880170000002',
    location: 'Remote • India',
    headline: 'Product Designer · Web & Mobile',
    source: 'Inbound',
    currentCompany: 'Northstar',
    currentTitle: 'Product Designer',
    linkedinUrl: 'https://www.linkedin.com/in/rohan-mehta',
    portfolioUrl: 'https://dribbble.com/rohan-designs',
    yearsExperience: 5,
    tags: ['Design', 'Figma', 'UX'],
  },
  {
    id: 'cand-3',
    organizationId: '1',
    fullName: 'Nabila Khan',
    email: 'nabila.khan@example.com',
    phone: '+880170000003',
    location: 'Singapore',
    headline: 'Data Analyst · SaaS',
    source: 'Job board',
    currentCompany: 'Dataview',
    currentTitle: 'Data Analyst',
    linkedinUrl: 'https://www.linkedin.com/in/nabila-khan',
    yearsExperience: 4,
    tags: ['SQL', 'Tableau', 'A/B testing'],
  },
  {
    id: 'cand-4',
    organizationId: '1',
    fullName: 'Aminul Islam',
    email: 'aminul.islam@example.com',
    phone: '+880170000004',
    location: 'Remote • EU',
    headline: 'QA Engineer · Automation',
    source: 'Agency',
    currentCompany: 'TestLab',
    currentTitle: 'QA Engineer',
    linkedinUrl: 'https://www.linkedin.com/in/aminul-islam',
    yearsExperience: 7,
    tags: ['Playwright', 'Cypress', 'API testing'],
  },
];
