import { JobStatus, SortingState } from '@prisma/client';

export const jobs = [
  {
    id: 'job-1',
    organizationId: '1',
    createdById: '2',
    title: 'Senior Backend Engineer',
    status: JobStatus.ACTIVE,
    sortingState: SortingState.COMPLETED,
    cvSortedCount: 128,
    cvAnalyzedCount: 92,
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    publishedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: 'job-2',
    organizationId: '1',
    createdById: '2',
    title: 'Product Manager, Growth',
    status: JobStatus.ACTIVE,
    sortingState: SortingState.PROCESSING,
    cvSortedCount: 96,
    cvAnalyzedCount: 70,
    lastActivityAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    publishedAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: 'job-3',
    organizationId: '1',
    createdById: '2',
    title: 'Data Analyst',
    status: JobStatus.REVIEWING,
    sortingState: SortingState.COMPLETED,
    cvSortedCount: 64,
    cvAnalyzedCount: 44,
    lastActivityAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    publishedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: 'job-4',
    organizationId: '1',
    createdById: '2',
    title: 'Frontend Engineer',
    status: JobStatus.DRAFT,
    sortingState: SortingState.NOT_STARTED,
    cvSortedCount: 18,
    cvAnalyzedCount: 0,
    lastActivityAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];
